---
- name: install cgit
  command: pkg -j {{ jailname }} install -y cgit
  args:
    creates: "/{{ jailhome }}/usr/local/www/cgit/cgit.cgi"
  environment:
    http_proxy: http://squid:3128/

- name: deploy cgitrc template
  template:
    src: cgitrc.j2
    dest: "{{ jailhome }}/usr/local/etc/cgitrc"

- name: create gitolite mountpoint
  file:
    dest: "{{ jailhome }}/usr/local/www/git"
    state: directory

- name: mount gitolite repodir
  mount:
    name: "{{ jailhome }}/rw/usr/local/www/git"
    src: /home/git/repositories
    fstype: nullfs
    opts: ro
    state: mounted
