---
- name: install fcgiwrap
  command: pkg -j {{ jailname }} install -y fcgiwrap
  args:
      creates: "{{ jailhome }}/usr/local/sbin/fcgiwrap"
  environment:
      http_proxy: http://squid:3128

- name: deploy fcgiwrap rc.conf template
  template:
    src: fcgiwrap.j2
    dest: "{{ jailhome}}/etc/rc.conf.d/fcgiwrap"
  notify: restart fcgiwrap
