---
- name: initialise VPS
  hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - { role: initialise, tags: ['initialise'] }

- name: configure VPS
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: openvpn, tags: [ 'initialise' ] }
    - { role: jails, tags: [ 'initialise' ] }
    - { role: firewall, tags: [ 'initialise' ] }
    - squid
    - bind
    - nginx
    - krb
    - ldap
