---
- name: bootstrap VPS
  hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - { role: bootstrap, tags: ['bootstrap'] }

- name: configure VPS
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: openvpn, tags: [ 'bootstrap' ] }
    - { role: jails, tags: [ 'bootstrap' ] }
    - { role: firewall, tags: [ 'bootstrap' ] }
    - squid
    - bind
    - nginx
    - krb
    - ldap
