---
- name: bootstrap VPS
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: bootstrap, tags: ['bootstrap'] }

- name: configure OpenVPN
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: openvpn, tags: ['openvpn'] }

- name: configure PF firewall
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: pf, tags: ['pf'] }

- name: configure ntpd
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: ntpd, tags: ['ntpd'] }

- name: configure postfix
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: postfix, tags: ['postfix'] }

- name: configure jails
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: jails, tags: ['jails'] }

- name: configure squid
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: squid, tags: ['squid'] }

- name: configure bind
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: bind, tags: ['bind'] }

- name: configure nginx
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: nginx, tags: ['nginx'] }

- name: configure radicale
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: radicale, tags: ['radicale'] }

- name: configure ldap
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: openldap, tags: ['ldap'] }
