---
- name: bootstrap VPS
  hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - { role: bootstrap, tags: ['bootstrap'] }

- name: configure OpenVPN
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: openvpn, tags: [ 'bootstrap' ] }

- name: configure PF firewall
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - { role: firewall, tags: [ 'bootstrap' ] }

- name: configure jails
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - jails

- name: configure squid
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - squid

- name: configure bind
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - bind

- name: configure nginx
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - nginx
