---
- name: initialise VPS
  hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - role: initialise

- name: setup OpenVPN
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: openvpn

- name: setup nginx
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: nginx

- name: setup bind
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: bind

- name: setup kerberos
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: krb

- name: setup PF firewall
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: firewall
