---
- name: initialise VPS
  hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - role: initialise
  tags:
    - initialise

- name: setup OpenVPN
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: openvpn
  tags:
    - initialise 

- name: setup jails
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: jails
  tags:
    - initialise

- name: setup PF firewall
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: firewall
  tags:
    - initialise

- name: setup squid
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: squid

- name: setup bind
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: bind

- name: setup nginx
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: nginx

- name: setup kerberos
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: krb

- name: setup ldap
  hosts: master
  remote_user: root
  gather_facts: true
  roles:
    - role: ldap
