---
- name: install postfix
  command: pkg install -y postfix
  args:
    creates: /usr/local/sbin/postfix

- name: enable postfix in rc.conf
  lineinfile: dest=/etc/rc.conf regexp=^postfix_enable= line=postfix_enable=\"YES\"

- name: deploy periodic.conf.local template
  template: src=periodic.conf.local.j2 dest=/etc/periodic.conf.local
              owner=root group=wheel mode=0644
  notify: restart postfix

- name: deploy mailer.conf template
  template: src=mailer.conf.j2 dest=/etc/mail/mailer.conf
              owner=root group=wheel mode=0644
  notify: restart postfix

- name: deploy postmix main.cf template
  template: src=main.cf.j2 dest=/usr/local/etc/postfix/main.cf
              owner=root group=wheel mode=0644
  notify:
    - restart postfix
    - postmap main.cf

- name: run newaliases
  command: /usr/bin/newaliases
  args:
    creates: /etc/mail/aliases.db
