---
- name: deploy local resolv.conf template
  template:
    src: resolv.conf.j2
    dest: "{{ jailhome }}/etc/resolv.conf"

- name: install radicale
  command: pkg -j {{ jailname }} install -y py37-radicale py37-ldap
  args:
    creates: "{{ jailhome }}/usr/local/etc/py37-radicale/config"
  environment:
    http_proxy: http://squid:3128/

- name: enable radicale in rc.conf
  lineinfile:
    dest: "{{ jailhome }}/etc/rc.conf"
    regexp: ^radicale_enable=
    line: radicale_enable="YES"

- name: deploy radicale config template
  template:
    src: config.j2
    dest: "{{ jailhome }}/usr/local/etc/py37-radicale/config"
  notify: restart radicale
