---
- name: install krb5
  command: pkg install -y krb5
  args:
    creates: /usr/local/sbin/kadmind

- name: enable kerberos kdc in rc.conf
  lineinfile: dest=/etc/rc.conf regexp=^kdc_enable= line=kdc_enable=\"YES\"

- name: enable kerberos kadmind in rc.conf
  lineinfile: dest=/etc/rc.conf regexp=^kadmind_enable= line=kadmind_enable=\"YES\"

- name: deploy krb5.conf template
  template: src=krb5.conf.j2 dest=/etc/krb5.conf
              owner=root group=wheel mode=0644
  notify: 
    - restart kerberos kdc
    - restart kerberos kadmind

- name: generate m-key
  command: kstash --random-key
  args:
    creates: /var/heimdal/m-key
  notify:
    - restart kerberos kdc
    - restart kerberos kadmind

- name: init LOCAL kerberos domain
  shell: echo $'init LOCAL\n\n\n' | kadmin -l
  args:
    creates: /var/heimdal/heimdal.db
  notify:
    - restart kerberos kdc
    - restart kerberos kadmind
