---
- name: deploy local resolv.conf
  copy: src=resolv.conf dest=/jailhome/krb/etc/resolv.conf

- name: install krb5
  command: pkg -j krb install -y krb5
  args:
    creates: /jailhome/krb/usr/local/sbin/kadmind
  environment:
    http_proxy: http://squid:3128/

- name: enable kerberos kdc in rc.conf
  lineinfile: dest=/jailhome/krb/etc/rc.conf regexp=^kdc_enable= line=kdc_enable=\"YES\"

- name: enable kerberos kadmind in rc.conf
  lineinfile: dest=/jailhome/krb/etc/rc.conf regexp=^kadmind_enable= line=kadmind_enable=\"YES\"

- name: deploy krb5.conf template
  template: src=krb5.conf.j2 dest=/jailhome/krb/etc/krb5.conf
              owner=root group=wheel mode=0644
  notify: 
    - restart kerberos kdc
    - restart kerberos kadmind

- name: generate m-key
  command: jexec krb kstash --random-key
  args:
    creates: /jailhome/krb/var/heimdal/m-key
  notify:
    - restart kerberos kdc
    - restart kerberos kadmind

- name: init LOCAL kerberos domain
  shell: echo $'init LOCAL\n\n\n' | jexec krb kadmin -l
  args:
    creates: /jailhome/krb/var/heimdal/heimdal.db
  notify:
    - restart kerberos kdc
    - restart kerberos kadmind
