---
- name: download jail base
  get_url: url=http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/amd64/{{ item }}-RELEASE/base.txz dest=/root/base.txz
  with_items:
      - "{{ freebsd_release }}"

- name:  deploy jail networking rc template
  template: src=network.j2 dest=/etc/rc.conf.d/network
  notify:
    - restart jail bridge
    - restart jails

- name: deploy jail rc template
  template: src=jail.j2 dest=/etc/rc.conf.d/jail
  notify:
    - restart jail bridge
    - restart jails

- name: deploy jail.conf template
  template: src=jail.conf.j2 dest=/etc/jail.conf
  notify:
    - restart jail bridge
    - restart jails

- name: create jail home
  file: dest=/jailhome state=directory

- name: create jail rootdirs
  file: dest=/jailhome/{{ item }} state=directory
  with_items: "{{ jails }}"
  notify:
    - restart jail bridge
    - restart jails

- name: extract jail rootdirs
  unarchive: src=/root/base.txz dest=/jailhome/{{ item }}/ copy=no
  with_items: "{{ jails }}"
  args:
    creates: /jailhome/{{ item }}/COPYRIGHT
  notify:
    - restart jail bridge
    - restart jails

- name: set jail FQDN
  lineinfile: dest=/jailhome/{{ item }}/etc/rc.conf regexp=^hostname= line=hostname={{ item }}.local create=yes
  with_items: "{{ jails }}"
  notify:
    - restart jails

- name: disable sendmail in rc.conf
  lineinfile: dest=/jailhome/{{ item }}/etc/rc.conf regexp='^sendmail_enable=' line='sendmail_enable=\"NONE\"'
  with_items: "{{ jails }}"
  notify:
    - restart jails

- name: add master alias to jail /etc/mail/aliases
  lineinfile: dest=/jailhome/{{ item }}/etc/mail/aliases regexp="^root:" line="root{{':'}} root@master.local"
  with_items: "{{ jails }}"

- name: run jail newaliases
  command: jail -c path=/jailhome/{{ item }} host.hostname={{ item }}.local command=/usr/bin/newaliases
  with_items: "{{ jails }}"
  args:
    creates: /jailhome/{{ item }}/etc/mail/aliases.db

- name: lock jail root
  lineinfile: dest=/jailhome/{{ item }}/etc/master.passwd regexp=^root line="root:*:0:0::0:0:rootuser:/root:/bin/csh" create=yes
  with_items: "{{ jails }}"
  notify:
    - restart jails

- name: deploy rc.conf.local overrides
  copy: src=rc.conf.local dest=/jailhome/{{ item }}/etc/rc.conf.local
  with_items: "{{ jails }}"
  notify:
    - restart jails
