---
- name: initialise pkg
  raw: echo y | ASSUME_ALWAYS_YES=yes /usr/sbin/pkg bootstrap

- name: update FreeBSD repository catalogue
  raw: /usr/sbin/pkg update -f

- name: install Python 
  raw: /usr/sbin/pkg install -y python

- name: set live hostname to master
  hostname: name=master

- name: set configured hostname to master
  lineinfile: dest=/etc/rc.conf regexp=^hostname= line=hostname=master
  notify: restart syslogd

- name: set crontab for daily NTP synchronisation
  lineinfile: dest=/etc/crontab regexp='^@daily root ntpdate -u pool.ntp.org' line='@daily root ntpdate -u pool.ntp.org'

- name: copy SSH daemon configuration
  copy: src=sshd_config dest=/etc/ssh/sshd_config
          owner=root group=wheel mode=0644
  notify: restart SSH daemon

- name: download portsnap archive
  command: portsnap fetch
  args:
    creates: /var/db/portsnap/INDEX

- name: extract portsnap archive
  command: portsnap extract
  args:
    creates: /usr/ports/net

- name: create ports distfiles dir
  file: dest=/usr/ports/distfiles state=directory

- name: download jail base
  get_url: url=ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/amd64/10.2-RELEASE/base.txz dest=/root/base.txz
