---
- name: deploy local resolv.conf template
  template:
    src: resolv.conf.j2
    dest: "{{ jailhome }}/etc/resolv.conf"

- name: install bind
  command: pkg -j {{ jailname }} install -y bind914
  args:
    creates: "{{ jailhome }}/usr/local/sbin/named"
  environment:
    http_proxy: "http://{{ jail_bridge_subnet}}.{{ squid_ip }}:3128/"

- name: enable named in rc.conf
  lineinfile:
    dest: "{{ jailhome }}/etc/rc.conf"
    regexp: ^named_enable=
    line: named_enable="YES"

- name: deploy named.conf template
  template:
    src: named.conf.j2
    dest: "{{ jailhome }}/usr/local/etc/namedb/named.conf"
  notify: restart named

- name: deploy local DNS zone
  template:
    src: dns.local.j2
    dest: "{{ jailhome }}/usr/local/etc/namedb/master/dns.local"
  notify: restart named

- name: deploy local reverse DNS template
  template:
    src: reversedns.local.j2
    dest: "{{ jailhome }}/usr/local/etc/namedb/master/reversedns.local"
  notify: restart named
