---
- name: install google DNS resolv.conf
  copy: src=resolv.conf dest=/jailhome/dns/etc/resolv.conf

- name: install bind
  command: pkg -j dns install -y bind910
  args:
    creates: /jailhome/dns/usr/local/sbin/named
  environment:
    http_proxy: http://{{ jail_bridge_subnet}}.10:3128/

- name: enable named in rc.conf
  lineinfile: dest=/jailhome/dns/etc/rc.conf regexp=^named_enable= line=named_enable=\"YES\"

- name: deploy named.conf template
  template: src=named.conf.j2 dest=/jailhome/dns/usr/local/etc/namedb/named.conf
              owner=root group=wheel mode=0644
  notify: restart named

- name: deploy local DNS zone
  template: src=dns.local.j2 dest=/jailhome/dns/usr/local/etc/namedb/master/dns.local
              owner=root group=wheel mode=0644
  notify: restart named

- name: deploy local reverse DNS template
  template: src=reversedns.local.j2 dest=/jailhome/dns/usr/local/etc/namedb/master/reversedns.local
              owner=root group=wheel mode=0644
  notify: restart named
