---
- name: install OpenVPN
  command: pkg install -y openvpn
  args:
    creates: /usr/local/sbin/openvpn

- name: create configuration directory
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - { path: '/usr/local/etc/openvpn', mode: '0644' }
    - { path: '/usr/local/etc/openvpn/ssl', mode: '0644' }
    - { path: '/usr/local/etc/openvpn/ssl/private', mode: '0600' }

- name: install OpenSSL public certificates
  template:
    src: "{{ item }}"
    dest: /usr/local/etc/openvpn/ssl
    mode: 0644
  with_items:
    - certificates/cacert.pem
    - certificates/openvpn.cert.pem
  notify: restart OpenVPN

- name: install OpenSSL private certificates
  template:
    src: "{{ item }}"
    dest: /usr/local/etc/openvpn/ssl/private
    mode: 0600
  with_items:
    - certificates/openvpn.key.pem
    - certificates/openvpn.dh2048.pem
    - certificates/tls-auth.pem
  notify: restart OpenVPN

- name: enable openvpn in rc.conf
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^openvpn_enable=
    line: openvpn_enable="YES"

- name: deploy openvpn.conf template
  template:
    src: openvpn.conf.j2
    dest: /usr/local/etc/openvpn/openvpn.conf
  notify: restart OpenVPN
